# Generated by Django 4.2 on 2023-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
                ('dia', models.DateField(auto_now_add=True)),
                ('calle', models.CharField(blank=True, max_length=255)),
                ('no_domicilio', models.IntegerField()),
                ('ciudad', models.CharField(max_length=255)),
            ],
        ),
    ]
