# Generated by Django 4.2 on 2023-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='deuda',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='metodoPago',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='total',
            field=models.IntegerField(default=True),
        ),
    ]
