# Generated by Django 4.2 on 2023-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_deuda_persona_metodopago_persona_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='deuda',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='metodoPago',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='total',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
