# Generated by Django 4.2 on 2023-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_deuda_alter_persona_metodopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='deuda',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='metodoPago',
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='total',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
